= Notes sur les bases des réseaux

== Vocabulaire

Liste de vocabulaire à retenir que selon moi est éssentiel.

=== Abbréviation

* *OSI* : Modèle (**O**pen **S**ystem **I**nterconnexion)
* *PCI* : **P**rotocol **C**ontrol **I**nformation
* *ISO* : **I**nternational **O**rganisation for **S**tandardisation
* *PDU* : **P**rotocol **D**ata **U**nit
* *SDU* : **S**ervice **D**ata **U**nit
* *PCI* : **P**rotocol **C**ontrol **I**nformation
* *CIDR* : **C**lassless **I**nter-**D**omain **R**outing


=== Définition

* Les *Protocoles* régissent l'ensemble des règles à respecter permettant la communication entre systèmes d'information en réseau.

* Le *PDU*, correspond à une unité de mesure des données échangés dans un réseau, il est constitué de plusieurs éléments :
** Des informations de contrôle de protocol (*PCI*)
** Des unité de services *SDU*
** *PDU* (N) = *SDU* (N) + *PCI* (N)
** Chaque couche ajoute à la donnée opaque qui est le *SDU* des informations de contrôle de protocole (*PCI*) pour obtenir un *PDU*. Tout comme le facteur qui ne voit pas le contenu d'une lettre (*SDU*) mais seulement l'adresse du destinataire (*PCI*) écrite sur l'enveloppe (*PDU*).

* *CIDR* : _**C**lassless **I**nter-**D**omain **R**outing_ : est une méthode de regroupement d'adresses IP utilisée sur le réseau Internet qui remplace le mécanisme de classes d'adresses (y compris masque de sous-réseau parfois utilisé à tord en remplacement de cidr), trop rigide.

* *ISO* (_**I**nternational **O**rganisation for **S**tandardisation_) : L'organisme internationale de normalisation met en place des normes, le modèle OSI repose sur la norme link:https://fr.wikipedia.org/wiki/Mod%C3%A8le_OSI[7498]

* Le *modèle OSI* est présenté en 7 couches indépendantes et communicantes, il représente la communication entre systèmes d'information en réseau (entre ordinateur).
Ce modèle est proposé par l'organisme de normalisation *ISO*.

=== Protocoles


* *IP (Internet Protocol)* | Ensemble de protocoles utilisés sur Internet et des les réseau locaux. 
* *FTP (File Transfer Protocol)* | Protocole conçue pour le transfère de fichiers
* *HTTP (Hyper Text Transfer Protocol)* | protocole de communication client-serveur pour le World Wild Web.
* *HTTPS (Hyper Text Transfer Protocol Secure)* | est la combinaison du protocole HTTP avec une 
couche de chiffrement comme le SSL ou TLS
* *SMTP (Simple Mail Transfer Protocol)* | en cours d'implémentation 
* *SSH (Secure SHell)* |  en cours d'implémentation 
* *IMAP (Internet Message Access Protocol)* |  en cours d'implémentation 
* *LDAP (Lightweight Directory Access Protocol)* |  en cours d'implémentation 
* *RDP (Remote Desktop Protocol)* |  en cours d'implémentation 
* *DNS (Domain Name Server)* |  en cours d'implémentation 
* *DHCP (Dynamic Host Configuration Protocol)* |  en cours d'implémentation 
* *SNMP (Simple Network Management Protocol)* |  en cours d'implémentation 
* *TLS (Transport Layer Secure)* | protocole de sécurisation
* *SSL (Secure Socket Layer)* | protocole de sécurisation

== Notes
